name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          config_order: base.header, isocalendar, languages
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.crypto.svg
          token: NOT_NEEDED
          base: ""
          plugin_crypto: yes
          plugin_crypto_id: bitcoin
          plugin_crypto_vs_currency: usd
          plugin_crypto_days: 1
          plugin_crypto_precision: 2
          
 

