name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_threshold: 2%                               # Hides all languages less than 2%
          plugin_isocalendar: yes
